# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
image: node:14.17.5

stages:
- build
- deploy

build prod:  
   stage: build  
   #only:    
   #   - tags  
   script:
      - npm install -g @angular/cli@13.0.4
      - npm install  
      - ng build --deploy-url /angular-ionic/
   artifacts:    
      paths:      
         # Build folder      
         - www/    
      expire_in: 1 week

pages: # the job must be named pages
  stage: deploy
  script:
      - rm -rf public
      - mkdir public
      - cp -r www/* public
    # optionally, you can activate gzip support with the following line:
      - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
      - public # artifact path must be /public for GitLab Pages to pick it up
  only:
      - main

