image: node:14.17.5

stages:
- build
- deploy

build prod:  
   stage: build
   script:
      - npm install -g @angular/cli@13.0.4
      - npm install  
      - ng build --deploy-url /angular-ionic/
   artifacts:    
      paths:      
         # Build folder      
         - www/    
      expire_in: 1 week

pages: # the job must be named pages
  stage: deploy
  script:
      - rm -rf public
      - mkdir public
      - cp -r www/* public
    # optionally, you can activate gzip support with the following line:
      - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
      - public
  only:
      - master

